# Generated by Django 5.0.4 on 2024-05-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
