# Generated by Django 5.0.4 on 2024-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_basket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(blank=True, default='Выполняется', max_length=255, null=True),
        ),
    ]
